name: notifychat
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # get state management
  get: ^4.6.6

  # firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.6
  firebase_database: ^11.1.6
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.4

  # notifications
  flutter_local_notifications: ^18.0.0

  # storage
  get_storage: ^2.1.1

  # ui components
  curved_navigation_bar: ^1.0.6
  flutter_custom_clippers: ^2.1.0
  bubble: ^1.2.1

  # responsive
  flutter_screenutil: ^5.9.3

  # google fonts
  google_fonts: ^6.2.1

  # uuid
  uuid: ^4.5.1

  # intl
  intl: ^0.20.1

  # connectivity
  connectivity_plus: ^6.1.1

  # svg
  flutter_svg: ^2.0.16

  # google sign in
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/vectors/
